AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Description: TrackerApp backend infrastructure.

Parameters:
  StageName:
    Type: String
    Default: v1
    Description: Enter the stage to use on API Gateway.

Globals:
  Function:
    Runtime: nodejs14.x
    MemorySize: 128
    Timeout: 15
    AutoPublishAlias: live
    Environment:
      Variables:
        JOURNEY_TABLE: !Ref TAppJourneyTable
        TOKEN_TABLE: !Ref TAppTokenTable

Resources:
  TAppJourneyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TAppJourneyTable
      AttributeDefinitions:
        - AttributeName: JourneyId
          AttributeType: S
      KeySchema:
        - AttributeName: JourneyId
          KeyType: HASH
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      TimeToLiveSpecification:
        AttributeName: TTL
        Enabled: true

  TAppTokenTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TAppTokenTable
      AttributeDefinitions:
        - AttributeName: ManagementToken
          AttributeType: S
      KeySchema:
        - AttributeName: ManagementToken
          KeyType: HASH
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      TimeToLiveSpecification:
        AttributeName: TTL
        Enabled: true

  TAppConnectionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TAppConnectionTable
      AttributeDefinitions:
        - AttributeName: ConnectionId
          AttributeType: S
      KeySchema:
        - AttributeName: ConnectionId
          KeyType: HASH
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false

  TAppRestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: TAppRestAPI
      EndpointConfiguration:
        Type: EDGE
      StageName: !Ref StageName
      OpenApiVersion: 3.0.1
      Auth:
        DefaultAuthorizer: TAppRestRequestAuthorizer
        Authorizers:
          TAppRestRequestAuthorizer:
            FunctionPayloadType: REQUEST
            FunctionArn: !GetAtt TAppTokenAuthFunction.Arn
            ReauthorizeEvery: 600
            Identity:
              Headers:
                - Authorization

  TAppJourneyGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TrackerApp-JourneyGet
      Handler: src/handlers/journey-get.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TAppJourneyTable
        - DynamoDBCrudPolicy:
            TableName: !Ref TAppTokenTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref TAppRestApi
            Method: GET
            Path: /journey/{id}

  TAppJourneyPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TrackerApp-JourneyPost
      Handler: src/handlers/journey-post.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TAppJourneyTable
        - DynamoDBCrudPolicy:
            TableName: !Ref TAppTokenTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref TAppRestApi
            Method: POST
            Path: /journey
            Auth:
              Authorizer: "NONE"

  TAppJourneyDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TrackerApp-JourneyDelete
      Handler: src/handlers/journey-delete.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TAppJourneyTable
        - DynamoDBCrudPolicy:
            TableName: !Ref TAppTokenTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref TAppRestApi
            Method: DELETE
            Path: /journey/{id}

  TAppLocationPutFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TrackerApp-LocationPut
      Handler: src/handlers/location-put.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TAppJourneyTable
        - DynamoDBCrudPolicy:
            TableName: !Ref TAppTokenTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref TAppRestApi
            Method: PUT
            Path: /journey/{id}/location

  TAppTokenAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TrackerApp-TokenAuth
      Handler: src/handlers/token-auth.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TAppJourneyTable
        - DynamoDBCrudPolicy:
            TableName: !Ref TAppTokenTable

  TAppJourneyGetFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ["/", ["/aws/lambda", !Ref TAppJourneyGetFunction]]
      RetentionInDays: 30

  TAppJourneyPostFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ["/", ["/aws/lambda", !Ref TAppJourneyPostFunction]]
      RetentionInDays: 30

  TAppJourneyDeleteFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ["/", ["/aws/lambda", !Ref TAppJourneyDeleteFunction]]
      RetentionInDays: 30

  TAppLocationPutFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ["/", ["/aws/lambda", !Ref TAppLocationPutFunction]]
      RetentionInDays: 30

  TAppTokenAuthFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ["/", ["/aws/lambda", !Ref TAppTokenAuthFunction]]
      RetentionInDays: 30

Outputs:
  TAppRestUrl:
    Description: "URL used to invoke TrackerApp REST endpoints."
    Value: !Sub "https://${TAppRestApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/"
